In [2]:
import tensorflow.compat.v1 as tf                   # 1.x 버전을 import
tf.disable_v2_behavior()                            # 2.x 버전을 비활성화

a = tf.constant(7.0, name = 'data1')               # constant: 상수
b = tf.constant(3.0, name = 'data2')
c = tf.constant(2.0, name = 'data3')

v = a * b / c

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(v))

10.5


In [3]:
import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior() 

input_data = [1, 2, 3, 4, 5]

x = tf.placeholder(dtype=tf.float32)
y = x * 2

sess = tf.Session()
result = sess.run(y, feed_dict={x:input_data})       # placeholder
sess.close()

print(result)

[ 2.  4.  6.  8. 10.]


In [6]:
import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior() 

p_holder1 = tf.placeholder(dtype=tf.float32)
p_holder2 = tf.placeholder(dtype=tf.float32)
p_holder3 = tf.placeholder(dtype=tf.float32)

val1 = 5
val2 = 10
val3 = 3

ret_val = p_holder1 * p_holder2 + p_holder3

sess = tf.Session()
feed_dict_data = {p_holder1: val1, p_holder2: val2, p_holder3: val3}
result = sess.run(ret_val, feed_dict=feed_dict_data)
sess.close()
print(result)

53.0


In [8]:
import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior() 

I = tf.Variable([[1, 2, 3, 4], [5, 6, 7, 8]], dtype = tf.float32)
W = tf.Variable([[1, 1], [2, 2], [3, 3], [4, 4]], dtype = tf.float32)

m_cal = tf.matmul(I, W)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

print(sess.run(m_cal))

sess.close()

[[30. 30.]
 [70. 70.]]


In [9]:
import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior() 

mat_img = [1, 2, 3, 4, 5]
label = [10, 20, 30, 40, 50]
ph_img = tf.placeholder(dtype = tf.float32)
ph_lb = tf.placeholder(dtype = tf.float32)

ret_tensor = ph_img + ph_lb

sess = tf.Session()
result = sess.run(ret_tensor, feed_dict={ph_img:mat_img, ph_lb:label}) 
sess.close()
print(result)

[11. 22. 33. 44. 55.]


In [13]:
import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior() 

data = [[2, 81], [4, 93], [6, 91], [8, 97]]
x_data = [x_row[0] for x_row in data]
y_data = [y_row[1] for y_row in data]

a = tf.Variable(tf.random_uniform([1], 0, 10, dtype = tf.float64, seed = 0))
b = tf.Variable(tf.random_uniform([1], 0, 100, dtype = tf.float64, seed = 0))

y = a * x_data + b

rmse = tf.sqrt(tf.reduce_mean(tf.square(y - y_data)))

learning_rate = 0.1

gradient_decent = tf.train.GradientDescentOptimizer(learning_rate).minimize(rmse)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(gradient_decent)
        if step % 100 == 0:
            print("Epoch: %.f, RMSE = %.04f, 기울기 a  = %.4f, y 절편 b = %.4f" % (step, sess.run(rmse), sess.run(a), sess.run(b)))

Epoch: 0, RMSE = 30.2139, 기울기 a  = 7.5235, y 절편 b = 80.5984
Epoch: 100, RMSE = 2.8860, 기울기 a  = 2.2299, y 절편 b = 79.4181
Epoch: 200, RMSE = 2.8826, 기울기 a  = 2.2601, y 절편 b = 79.2379
Epoch: 300, RMSE = 2.8815, 기울기 a  = 2.2773, y 절편 b = 79.1353
Epoch: 400, RMSE = 2.8811, 기울기 a  = 2.2871, y 절편 b = 79.0770
Epoch: 500, RMSE = 2.8810, 기울기 a  = 2.2927, y 절편 b = 79.0438
Epoch: 600, RMSE = 2.8810, 기울기 a  = 2.2958, y 절편 b = 79.0249
Epoch: 700, RMSE = 2.8810, 기울기 a  = 2.2976, y 절편 b = 79.0142
Epoch: 800, RMSE = 2.8810, 기울기 a  = 2.2987, y 절편 b = 79.0081
Epoch: 900, RMSE = 2.8810, 기울기 a  = 2.2992, y 절편 b = 79.0046
Epoch: 1000, RMSE = 2.8810, 기울기 a  = 2.2996, y 절편 b = 79.0026
Epoch: 1100, RMSE = 2.8810, 기울기 a  = 2.2998, y 절편 b = 79.0015
Epoch: 1200, RMSE = 2.8810, 기울기 a  = 2.2999, y 절편 b = 79.0008
Epoch: 1300, RMSE = 2.8810, 기울기 a  = 2.2999, y 절편 b = 79.0005
Epoch: 1400, RMSE = 2.8810, 기울기 a  = 2.3000, y 절편 b = 79.0003
Epoch: 1500, RMSE = 2.8810, 기울기 a  = 2.3000, y 절편 b = 79.0002
Epoch: 1600, RMSE =

In [21]:
import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior() 

data = [[1, 0.2], [2, 0.3], [3, 0.5], [4, 0.6], [5, 0.9], [6, 0.95], [7, 1.1], [8, 1.5]]
x_data = [x_row[0] for x_row in data]
y_data = [y_row[1] for y_row in data]

a = tf.Variable(0.,  dtype = tf.float64)
b = tf.Variable(0., dtype = tf.float64)

y = a * x_data + b

rmse = tf.sqrt(tf.reduce_mean(tf.square(y - y_data)))

learning_rate = 0.001

gradient_decent = tf.train.GradientDescentOptimizer(learning_rate).minimize(rmse)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(5001):
        sess.run(gradient_decent)
        if step % 100 == 0:
            print("Epoch: %.f, RMSE = %.04f, 기울기 a  = %.4f, y 절편 b = %.4f" % (step, sess.run(rmse), sess.run(a), sess.run(b)))

Epoch: 0, RMSE = 0.8336, 기울기 a  = 0.0050, y 절편 b = 0.0009
Epoch: 100, RMSE = 0.0763, 기울기 a  = 0.1664, y 절편 b = 0.0179
Epoch: 200, RMSE = 0.0748, 기울기 a  = 0.1685, y 절편 b = 0.0059
Epoch: 300, RMSE = 0.0739, 기울기 a  = 0.1702, y 절편 b = -0.0035
Epoch: 400, RMSE = 0.0734, 기울기 a  = 0.1715, y 절편 b = -0.0108
Epoch: 500, RMSE = 0.0730, 기울기 a  = 0.1725, y 절편 b = -0.0163
Epoch: 600, RMSE = 0.0729, 기울기 a  = 0.1732, y 절편 b = -0.0205
Epoch: 700, RMSE = 0.0728, 기울기 a  = 0.1738, y 절편 b = -0.0237
Epoch: 800, RMSE = 0.0727, 기울기 a  = 0.1742, y 절편 b = -0.0262
Epoch: 900, RMSE = 0.0727, 기울기 a  = 0.1745, y 절편 b = -0.0281
Epoch: 1000, RMSE = 0.0726, 기울기 a  = 0.1748, y 절편 b = -0.0295
Epoch: 1100, RMSE = 0.0726, 기울기 a  = 0.1750, y 절편 b = -0.0305
Epoch: 1200, RMSE = 0.0726, 기울기 a  = 0.1751, y 절편 b = -0.0314
Epoch: 1300, RMSE = 0.0726, 기울기 a  = 0.1752, y 절편 b = -0.0320
Epoch: 1400, RMSE = 0.0726, 기울기 a  = 0.1753, y 절편 b = -0.0324
Epoch: 1500, RMSE = 0.0726, 기울기 a  = 0.1754, y 절편 b = -0.0328
Epoch: 1600, RMSE = 0.0

In [23]:
import tensorflow.compat.v1 as tf 
tf.disable_v2_behavior() 

data = [[2, 0, 81], [4, 4, 93], [6, 2, 91], [8, 3, 97]]
x1 = [x_row1[0] for x_row1 in data]
x2 = [x_row2[1] for x_row2 in data]
y_data = [y_row[2] for y_row in data]

a1 = tf.Variable(tf.random_uniform([1], 0, 10, dtype = tf.float64, seed = 0))
b = tf.Variable(tf.random_uniform([1], 0, 100, dtype = tf.float64, seed = 0))
a2 = tf.Variable(tf.random_uniform([1], 0, 10, dtype = tf.float64, seed = 0))

y = a1 * x1 + a2 * x2 + b

rmse = tf.sqrt(tf.reduce_mean(tf.square(y - y_data)))

learning_rate = 0.1

gradient_decent = tf.train.GradientDescentOptimizer(learning_rate).minimize(rmse)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(gradient_decent)
        if step % 100 == 0:
            print("Epoch: %.f, RMSE = %.04f, 기울기 a1  = %.4f, 기울기 a2 = %.4f, y 절편 b = %.4f" % (step, sess.run(rmse), sess.run(a1), sess.run(a2), sess.run(b)))

Epoch: 0, RMSE = 49.1842, 기울기 a1  = 7.5270, 기울기 a2 = 7.8160, y 절편 b = 80.5980
Epoch: 100, RMSE = 1.8368, 기울기 a1  = 1.1306, 기울기 a2 = 2.1316, y 절편 b = 78.5119
Epoch: 200, RMSE = 1.8370, 기울기 a1  = 1.1879, 기울기 a2 = 2.1487, y 절편 b = 78.1057
Epoch: 300, RMSE = 1.8370, 기울기 a1  = 1.2122, 기울기 a2 = 2.1571, y 절편 b = 77.9352
Epoch: 400, RMSE = 1.8370, 기울기 a1  = 1.2226, 기울기 a2 = 2.1607, y 절편 b = 77.8636
Epoch: 500, RMSE = 1.8370, 기울기 a1  = 1.2269, 기울기 a2 = 2.1622, y 절편 b = 77.8335
Epoch: 600, RMSE = 1.8370, 기울기 a1  = 1.2288, 기울기 a2 = 2.1628, y 절편 b = 77.8208
Epoch: 700, RMSE = 1.8370, 기울기 a1  = 1.2295, 기울기 a2 = 2.1631, y 절편 b = 77.8155
Epoch: 800, RMSE = 1.8370, 기울기 a1  = 1.2299, 기울기 a2 = 2.1632, y 절편 b = 77.8133
Epoch: 900, RMSE = 1.8370, 기울기 a1  = 1.2300, 기울기 a2 = 2.1632, y 절편 b = 77.8124
Epoch: 1000, RMSE = 1.8370, 기울기 a1  = 1.2301, 기울기 a2 = 2.1633, y 절편 b = 77.8120
Epoch: 1100, RMSE = 1.8370, 기울기 a1  = 1.2301, 기울기 a2 = 2.1633, y 절편 b = 77.8118
Epoch: 1200, RMSE = 1.8370, 기울기 a1  = 1.2301, 기울기 a